2014/11/21 15:50:54 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
' in C:\xampp\htdocs\www\framework\db\CDbConnection.php:381
Stack trace:
#0 C:\xampp\htdocs\www\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\www\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\www\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\www\framework\web\CDbHttpSession.php(160): CModule->getComponent('db')
#4 C:\xampp\htdocs\www\framework\web\CDbHttpSession.php(206): CDbHttpSession->getDbConnection()
#5 [internal function]: CDbHttpSession->readSession('r7gngknvqpl57ba...')
#6 C:\xampp\htdocs\www\framework\web\CHttpSession.php(118): session_start()
#7 C:\xampp\htdocs\www\framework\web\CHttpSession.php(92): CHttpSession->open()
#8 C:\xampp\htdocs\www\framework\base\CModule.php(387): CHttpSession->init()
#9 C:\xampp\htdocs\www\framework\base\CModule.php(103): CModule->getComponent('session')
#10 C:\xampp\htdocs\www\pos.local\protected\components\Controller.php(28): CModule->__get('session')
#11 C:\xampp\htdocs\www\framework\web\CWebApplication.php(281): Controller->init()
#12 C:\xampp\htdocs\www\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#13 C:\xampp\htdocs\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#14 C:\xampp\htdocs\www\pos.local\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/
---
2014/11/21 15:50:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\www\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\www\pos.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2014/11/21 15:51:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\www\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\www\pos.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2014/11/21 18:04:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "inventorycenter/tree_data1.json".' in C:\xampp\htdocs\www\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\www\framework\web\CWebApplication.php(141): CWebApplication->runController('inventorycenter...')
#1 C:\xampp\htdocs\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\www\pos.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/inventorycenter/tree_data1.json
HTTP_REFERER=http://pos.local/inventorycenter/customers
---
2014/11/21 18:05:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "inventorycenter/tree_data1.json".' in C:\xampp\htdocs\www\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\www\framework\web\CWebApplication.php(141): CWebApplication->runController('inventorycenter...')
#1 C:\xampp\htdocs\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\www\pos.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/inventorycenter/tree_data1.json
HTTP_REFERER=http://pos.local/inventorycenter/customers
---
2014/11/21 18:07:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "inventorycenter/tree_data1.json".' in C:\xampp\htdocs\www\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\www\framework\web\CWebApplication.php(141): CWebApplication->runController('inventorycenter...')
#1 C:\xampp\htdocs\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\www\pos.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/inventorycenter/tree_data1.json
HTTP_REFERER=http://pos.local/inventorycenter/customers
---
2014/11/21 18:07:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "inventorycenter/tree_data1.json".' in C:\xampp\htdocs\www\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\www\framework\web\CWebApplication.php(141): CWebApplication->runController('inventorycenter...')
#1 C:\xampp\htdocs\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\www\pos.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/inventorycenter/tree_data1.json
HTTP_REFERER=http://pos.local/inventorycenter/customers
---
2014/11/21 18:12:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "inventorycenter/tree_data1.json".' in C:\xampp\htdocs\www\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\www\framework\web\CWebApplication.php(141): CWebApplication->runController('inventorycenter...')
#1 C:\xampp\htdocs\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\www\pos.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/inventorycenter/tree_data1.json
HTTP_REFERER=http://pos.local/inventorycenter/customers
---
2014/11/21 18:13:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "inventorycenter/tree_data1.json".' in C:\xampp\htdocs\www\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\www\framework\web\CWebApplication.php(141): CWebApplication->runController('inventorycenter...')
#1 C:\xampp\htdocs\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\www\pos.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/inventorycenter/tree_data1.json
HTTP_REFERER=http://pos.local/inventorycenter/customers
---
2014/11/21 18:22:45 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
' in C:\xampp\htdocs\www\framework\db\CDbConnection.php:381
Stack trace:
#0 C:\xampp\htdocs\www\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\www\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\www\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\www\framework\web\CDbHttpSession.php(160): CModule->getComponent('db')
#4 C:\xampp\htdocs\www\framework\web\CDbHttpSession.php(206): CDbHttpSession->getDbConnection()
#5 [internal function]: CDbHttpSession->readSession('r7gngknvqpl57ba...')
#6 C:\xampp\htdocs\www\framework\web\CHttpSession.php(118): session_start()
#7 C:\xampp\htdocs\www\framework\web\CHttpSession.php(92): CHttpSession->open()
#8 C:\xampp\htdocs\www\framework\base\CModule.php(387): CHttpSession->init()
#9 C:\xampp\htdocs\www\framework\base\CModule.php(103): CModule->getComponent('session')
#10 C:\xampp\htdocs\www\pos.local\protected\components\Controller.php(28): CModule->__get('session')
#11 C:\xampp\htdocs\www\framework\web\CWebApplication.php(281): Controller->init()
#12 C:\xampp\htdocs\www\framework\web\CWebApplication.php(141): CWebApplication->runController('dashboard')
#13 C:\xampp\htdocs\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#14 C:\xampp\htdocs\www\pos.local\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/dashboard
---
2014/11/21 18:22:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\www\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\www\pos.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2014/11/21 18:22:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\www\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\www\pos.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2014/11/21 18:23:15 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
' in C:\xampp\htdocs\www\framework\db\CDbConnection.php:381
Stack trace:
#0 C:\xampp\htdocs\www\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\www\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\www\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\www\framework\web\CDbHttpSession.php(160): CModule->getComponent('db')
#4 C:\xampp\htdocs\www\framework\web\CDbHttpSession.php(206): CDbHttpSession->getDbConnection()
#5 [internal function]: CDbHttpSession->readSession('r7gngknvqpl57ba...')
#6 C:\xampp\htdocs\www\framework\web\CHttpSession.php(118): session_start()
#7 C:\xampp\htdocs\www\framework\web\CHttpSession.php(92): CHttpSession->open()
#8 C:\xampp\htdocs\www\framework\base\CModule.php(387): CHttpSession->init()
#9 C:\xampp\htdocs\www\framework\base\CModule.php(103): CModule->getComponent('session')
#10 C:\xampp\htdocs\www\pos.local\protected\components\Controller.php(28): CModule->__get('session')
#11 C:\xampp\htdocs\www\framework\web\CWebApplication.php(281): Controller->init()
#12 C:\xampp\htdocs\www\framework\web\CWebApplication.php(141): CWebApplication->runController('dashboard')
#13 C:\xampp\htdocs\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#14 C:\xampp\htdocs\www\pos.local\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/dashboard
---
2014/11/21 18:23:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "inventorycenter/tree_data1.json".' in C:\xampp\htdocs\www\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\www\framework\web\CWebApplication.php(141): CWebApplication->runController('inventorycenter...')
#1 C:\xampp\htdocs\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\www\pos.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/inventorycenter/tree_data1.json
HTTP_REFERER=http://pos.local/inventorycenter/customers
---
2014/11/21 18:33:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "inventorycenter/tree_data1.json".' in C:\xampp\htdocs\www\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\www\framework\web\CWebApplication.php(141): CWebApplication->runController('inventorycenter...')
#1 C:\xampp\htdocs\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\www\pos.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/inventorycenter/tree_data1.json
HTTP_REFERER=http://pos.local/inventorycenter/customers
---
2014/11/21 18:36:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "inventorycenter/tree_data1.json".' in C:\xampp\htdocs\www\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\www\framework\web\CWebApplication.php(141): CWebApplication->runController('inventorycenter...')
#1 C:\xampp\htdocs\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\www\pos.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/inventorycenter/tree_data1.json
HTTP_REFERER=http://pos.local/inventorycenter/customers
---
2014/11/21 18:36:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "inventorycenter/tree_data1.json".' in C:\xampp\htdocs\www\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\www\framework\web\CWebApplication.php(141): CWebApplication->runController('inventorycenter...')
#1 C:\xampp\htdocs\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\www\pos.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/inventorycenter/tree_data1.json
HTTP_REFERER=http://pos.local/inventorycenter/customers
---
2014/11/21 18:42:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "inventorycenter/tree_data1.json".' in C:\xampp\htdocs\www\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\www\framework\web\CWebApplication.php(141): CWebApplication->runController('inventorycenter...')
#1 C:\xampp\htdocs\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\www\pos.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/inventorycenter/tree_data1.json
HTTP_REFERER=http://pos.local/inventorycenter/customers
---
2014/11/21 18:47:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "inventorycenter/tree_data1.json".' in C:\xampp\htdocs\www\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\www\framework\web\CWebApplication.php(141): CWebApplication->runController('inventorycenter...')
#1 C:\xampp\htdocs\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\www\pos.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/inventorycenter/tree_data1.json
HTTP_REFERER=http://pos.local/inventorycenter/customers
---
2014/11/21 18:54:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "inventorycenter/tree_data1.json".' in C:\xampp\htdocs\www\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\www\framework\web\CWebApplication.php(141): CWebApplication->runController('inventorycenter...')
#1 C:\xampp\htdocs\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\www\pos.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/inventorycenter/tree_data1.json
HTTP_REFERER=http://pos.local/inventorycenter/customers
---
2014/11/21 18:56:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "inventorycenter/tree_data1.json".' in C:\xampp\htdocs\www\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\www\framework\web\CWebApplication.php(141): CWebApplication->runController('inventorycenter...')
#1 C:\xampp\htdocs\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\www\pos.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/inventorycenter/tree_data1.json
HTTP_REFERER=http://pos.local/inventorycenter/customers
---
2014/11/21 18:58:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "inventorycenter/tree_data1.json".' in C:\xampp\htdocs\www\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\www\framework\web\CWebApplication.php(141): CWebApplication->runController('inventorycenter...')
#1 C:\xampp\htdocs\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\www\pos.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/inventorycenter/tree_data1.json
HTTP_REFERER=http://pos.local/inventorycenter/customers
---
